##
## "Standard" Docker Compose file for local development
## Builds and deploys locally
##

services:
  server:
    platform: "linux/amd64"
    container_name: "mutiny-link-shortener"
    build:
      context: .
      dockerfile: Dockerfile
    env_file:
      - path: .env
        required: true
    networks:
      - web
    ports:
      - 3000:3000

networks:
  web:
    driver: bridge
