##
## Docker Compose/Swarm config file for Github Actions-based
## development CI/CD on Portainer.
##

services:
  shortener:
    image: "ghcr.io/adammakesthingsdev/mutiny-link-shortener:latest"
    container_name: "link-shortener"

    networks:
      - bridge

    environment:
      - AUTH_SECRET
      - AUTH_GITHUB_ID
      - AUTH_GITHUB_SECRET
      - DATABASE_URL
      - DIRECT_URL
      - ADMIN_API_KEY

    deploy:
      update_config:
        order: start-first

networks:
  bridge:
    external:
      name: bridge
