##
## This action deploys a development build to a private
## Docker development server (running Portainer).
##

name: Deploy to development server

# Should run only once build is complete
on:
  workflow_dispatch:
  workflow_run:
    workflows: ["Publish to Github Packages"]
    types: [completed]

jobs:
  deploy:
    name: Deploy to dev
    runs-on: ubuntu-latest
    timeout-minutes: 20
    environment: development

    env:
      AUTH_SECRET: ${{secrets.LINK_AUTH_SECRET}}
      AUTH_GITHUB_ID: ${{secrets.LINK_AUTH_GITHUB_ID}}
      AUTH_GITHUB_SECRET: ${{secrets.LINK_AUTH_GITHUB_SECRET}}
      DATABASE_URL: ${{secrets.LINK_DATABASE_URL}}
      DIRECT_URL: ${{secrets.LINK_DIRECT_URL}}
      ADMIN_API_KEY: ${{secrets.LINK_ADMIN_API_KEY}}

    steps:
      - uses: actions/checkout@v2

      - name: Deploy stack to Portainer
        uses: carlrygart/portainer-stack-deploy@v1
        with:
          portainer-host: ${{secrets.PORTAINER_HOST}}
          username: ${{secrets.PORTAINER_USERNAME}}
          password: ${{secrets.PORTAINER_PASSWORD}}
          stack-name: ${{vars.STACK_NAME}}
          stack-definition: docker/compose.dev.yaml
          template-variables: '{"image-url":"${{vars.IMAGE_URL}}:latest"}'
